{% set name = "fps-terminals" %}
{% set version = "0.9.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/fps_terminals-{{ version }}.tar.gz
  sha256: 81a16b9ffb2add244c3da0d78794c12af1013602d5fba6f013fc2519037f15d4

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - uv-build                               # [build_platform != target_platform]
  host:
    - python
    - pip
    - uv-build
  run:
    - python
    - jupyverse-api >=0.13.0,<0.14.0
    - pywinpty  # [win]
    - anyio >=4.9.0,<5.0.0

test:
  requires:
    - pip
  commands:
    - pip check
  imports:
    - fps_terminals

about:
  home: https://github.com/jupyter-server/jupyverse/tree/main/plugins/terminals
  summary: An FPS plugin for the terminals API
  keywords: jupyter, server, fastapi, plugins
  dev_url: https://github.com/jupyter-server/jupyverse/tree/main/plugins/terminals
  license_file: COPYING.md
  license: BSD-3-Clause
  license_family: BSD

extra:
  recipe-maintainers:
    - davidbrochart
